[project]
name = "user-profile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lrast", email = "luke.rast@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
user-profile = "user_profile:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
